using UnityEngine;
using UnityEngine.UI;
using System.Collections;
using TMPro;

[System.Serializable]
public class PlayPageDetail
{
    public UIItem HangUp_UIItem;
    public Image CancelHangUpBtn_Image;
    public Button CancelHangUpBtn_Button;
    public Image DropButton_Image;
    public Button DropButton_Button;
    public Image ExitButton_Image;
    public Button ExitButton_Button;
    public Image PopupButton_Image;
    public Button PopupButton_Button;
    public Image DismissButton_Image;
    public Button DismissButton_Button;
    public Image Image1_Image;
    public Image Image_Image;
    public Text CardNum_Text;
    public Text Time_Text;
    public UIItem CtrlPanel_UIItem;
    public Image PassButton_Image;
    public Button PassButton_Button;
    public HorizontalLayoutGroup Root_HorizontalLayoutGroup;
    public Image GangButton_Image;
    public Button GangButton_Button;
    public LayoutElement GangButton_LayoutElement;
    public Image PengButton_Image;
    public Button PengButton_Button;
    public LayoutElement PengButton_LayoutElement;
    public Image ChiButton_Image;
    public Button ChiButton_Button;
    public LayoutElement ChiButton_LayoutElement;
    public Image HuButton_Image;
    public Button HuButton_Button;
    public LayoutElement HuButton_LayoutElement;
    public Image TingButton_Image;
    public Button TingButton_Button;
    public LayoutElement TingButton_LayoutElement;
    public Image TingPengButton_Image;
    public Button TingPengButton_Button;
    public LayoutElement TingPengButton_LayoutElement;
    public Image TingChiButton_Image;
    public Button TingChiButton_Button;
    public LayoutElement TingChiButton_LayoutElement;
    public Image ZhiduiButton_Image;
    public Button ZhiduiButton_Button;
    public LayoutElement ZhiduiButton_LayoutElement;
    public UIItem SelectPanel_UIItem;
    public HorizontalLayoutGroup SelectRoot_HorizontalLayoutGroup;
    public Image CancelButton_Image;
    public Button CancelButton_Button;
    public Image GroupButton_Image;
    public Button GroupButton_Button;
    public GridLayoutGroup GroupButton_GridLayoutGroup;
    public PlayerSub PlayerSub0_PlayerSub;
    public PlayerSub PlayerSub1_PlayerSub;
    public PlayerSub PlayerSub2_PlayerSub;
    public PlayerSub PlayerSub3_PlayerSub;
    public EffectPos EffectPos_EffectPos;
    public Image VoiceButton_Image;
    public Button VoiceButton_Button;
    public Image ChatButton_Image;
    public Button ChatButton_Button;
    public Image DetailButton_Image;
    public Button DetailButton_Button;
    public Image GameRoundButton_Image;
    public Button GameRoundButton_Button;
    public Text GameRoundText_Text;
    public Image WXButton_Image;
    public Button WXButton_Button;
    public MicrophoneInput AudioSource_MicrophoneInput;
    public UIItem PopupMenu_UIItem;
    public Image ClosePopButton_Image;
    public Button ClosePopButton_Button;
    public Image HostedButton_Image;
    public Button HostedButton_Button;
    public Image SettingButton_Image;
    public Button SettingButton_Button;
    public UIItem RecodState_UIItem;
    public Text CountDown_Text;
    public Shadow CountDown_Shadow;
    public Image DumpBtn_Image;
    public Button DumpBtn_Button;
    public Text Text_Text;

}