//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Assets/ProtoBuffMsg/Hall.proto
namespace packet.game
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AntiAddictionRequest")]
  public partial class AntiAddictionRequest : global::ProtoBuf.IExtensible
  {
    public AntiAddictionRequest() {}
    
    private string _phoneNumber = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"phoneNumber", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string phoneNumber
    {
      get { return _phoneNumber; }
      set { _phoneNumber = value; }
    }
    private string _playerIdentityNumber = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerIdentityNumber", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerIdentityNumber
    {
      get { return _playerIdentityNumber; }
      set { _playerIdentityNumber = value; }
    }
    private string _playerRealName = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"playerRealName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerRealName
    {
      get { return _playerRealName; }
      set { _playerRealName = value; }
    }
    private string _playerAddress = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"playerAddress", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerAddress
    {
      get { return _playerAddress; }
      set { _playerAddress = value; }
    }
    private string _playerWeiXinID = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"playerWeiXinID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerWeiXinID
    {
      get { return _playerWeiXinID; }
      set { _playerWeiXinID = value; }
    }
    private string _playerQQID = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"playerQQID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerQQID
    {
      get { return _playerQQID; }
      set { _playerQQID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AntiAddictionResponse")]
  public partial class AntiAddictionResponse : global::ProtoBuf.IExtensible
  {
    public AntiAddictionResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegisterRequest")]
  public partial class RegisterRequest : global::ProtoBuf.IExtensible
  {
    public RegisterRequest() {}
    
    private string _account = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private string _nickname = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"nickname", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickname
    {
      get { return _nickname; }
      set { _nickname = value; }
    }
    private int _deviceFlag = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"deviceFlag", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int deviceFlag
    {
      get { return _deviceFlag; }
      set { _deviceFlag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RegisterResponse")]
  public partial class RegisterResponse : global::ProtoBuf.IExtensible
  {
    public RegisterResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VistorRegisterRequest")]
  public partial class VistorRegisterRequest : global::ProtoBuf.IExtensible
  {
    public VistorRegisterRequest() {}
    
    private int _deviceFlag = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"deviceFlag", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int deviceFlag
    {
      get { return _deviceFlag; }
      set { _deviceFlag = value; }
    }
    private string _deviceId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"deviceId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string deviceId
    {
      get { return _deviceId; }
      set { _deviceId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VistorRegisterResponse")]
  public partial class VistorRegisterResponse : global::ProtoBuf.IExtensible
  {
    public VistorRegisterResponse() {}
    
    private string _account = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _password = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomResultRequest")]
  public partial class RoomResultRequest : global::ProtoBuf.IExtensible
  {
    public RoomResultRequest() {}
    
    private long _roomId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomResultResponse")]
  public partial class RoomResultResponse : global::ProtoBuf.IExtensible
  {
    public RoomResultResponse() {}
    
    private readonly global::System.Collections.Generic.List<packet.game.RoomResultModel> _list = new global::System.Collections.Generic.List<packet.game.RoomResultModel>();
    [global::ProtoBuf.ProtoMember(1, Name=@"list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<packet.game.RoomResultModel> list
    {
      get { return _list; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomResultModel")]
  public partial class RoomResultModel : global::ProtoBuf.IExtensible
  {
    public RoomResultModel() {}
    
    private long _roomId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private string _roomName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomName
    {
      get { return _roomName; }
      set { _roomName = value; }
    }
    private string _roomCode = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomCode
    {
      get { return _roomCode; }
      set { _roomCode = value; }
    }
    private string _playerTime = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"playerTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerTime
    {
      get { return _playerTime; }
      set { _playerTime = value; }
    }
    private readonly global::System.Collections.Generic.List<packet.game.PlayerScoreModel> _playerScore = new global::System.Collections.Generic.List<packet.game.PlayerScoreModel>();
    [global::ProtoBuf.ProtoMember(5, Name=@"playerScore", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<packet.game.PlayerScoreModel> playerScore
    {
      get { return _playerScore; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerScoreModel")]
  public partial class PlayerScoreModel : global::ProtoBuf.IExtensible
  {
    public PlayerScoreModel() {}
    
    private string _playerName = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"playerName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerName
    {
      get { return _playerName; }
      set { _playerName = value; }
    }
    private long _playerId = default(long);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _score = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MallProductRequest")]
  public partial class MallProductRequest : global::ProtoBuf.IExtensible
  {
    public MallProductRequest() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MallProductResponse")]
  public partial class MallProductResponse : global::ProtoBuf.IExtensible
  {
    public MallProductResponse() {}
    
    private readonly global::System.Collections.Generic.List<packet.game.MallProductModel> _products = new global::System.Collections.Generic.List<packet.game.MallProductModel>();
    [global::ProtoBuf.ProtoMember(1, Name=@"products", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<packet.game.MallProductModel> products
    {
      get { return _products; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MallProductModel")]
  public partial class MallProductModel : global::ProtoBuf.IExtensible
  {
    public MallProductModel() {}
    
    private string _id = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"id", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string id
    {
      get { return _id; }
      set { _id = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private string _image = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"image", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string image
    {
      get { return _image; }
      set { _image = value; }
    }
    private int _category = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"category", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int category
    {
      get { return _category; }
      set { _category = value; }
    }
    private int _price = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int price
    {
      get { return _price; }
      set { _price = value; }
    }
    private int _itemCount = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"itemCount", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int itemCount
    {
      get { return _itemCount; }
      set { _itemCount = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GenOrderRequest")]
  public partial class GenOrderRequest : global::ProtoBuf.IExtensible
  {
    public GenOrderRequest() {}
    
    private int _platformId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"platformId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int platformId
    {
      get { return _platformId; }
      set { _platformId = value; }
    }
    private string _productId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"productId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string productId
    {
      get { return _productId; }
      set { _productId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GenOrderResponse")]
  public partial class GenOrderResponse : global::ProtoBuf.IExtensible
  {
    public GenOrderResponse() {}
    
    private string _orderId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"orderId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string orderId
    {
      get { return _orderId; }
      set { _orderId = value; }
    }
    private int _platformId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"platformId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int platformId
    {
      get { return _platformId; }
      set { _platformId = value; }
    }
    private byte[] _data = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ConfirmOrderRequest")]
  public partial class ConfirmOrderRequest : global::ProtoBuf.IExtensible
  {
    public ConfirmOrderRequest() {}
    
    private string _orderId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"orderId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string orderId
    {
      get { return _orderId; }
      set { _orderId = value; }
    }
    private int _platformId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"platformId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int platformId
    {
      get { return _platformId; }
      set { _platformId = value; }
    }
    private int _result = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"result", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int result
    {
      get { return _result; }
      set { _result = value; }
    }
    private byte[] _data = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomConfigResponse")]
  public partial class RoomConfigResponse : global::ProtoBuf.IExtensible
  {
    public RoomConfigResponse() {}
    
    private readonly global::System.Collections.Generic.List<packet.game.RoomConfigModel> _roomList = new global::System.Collections.Generic.List<packet.game.RoomConfigModel>();
    [global::ProtoBuf.ProtoMember(1, Name=@"roomList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<packet.game.RoomConfigModel> roomList
    {
      get { return _roomList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"RoomConfigModel")]
  public partial class RoomConfigModel : global::ProtoBuf.IExtensible
  {
    public RoomConfigModel() {}
    
    private string _roomId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private string _roomName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"roomName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomName
    {
      get { return _roomName; }
      set { _roomName = value; }
    }
    private string _roomType = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private string _matchType = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"matchType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string matchType
    {
      get { return _matchType; }
      set { _matchType = value; }
    }
    private int _baseScore = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"baseScore", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int baseScore
    {
      get { return _baseScore; }
      set { _baseScore = value; }
    }
    private int _minCoinLimit = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"minCoinLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int minCoinLimit
    {
      get { return _minCoinLimit; }
      set { _minCoinLimit = value; }
    }
    private int _maxCoinLimit = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"maxCoinLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxCoinLimit
    {
      get { return _maxCoinLimit; }
      set { _maxCoinLimit = value; }
    }
    private string _icon = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"icon", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string icon
    {
      get { return _icon; }
      set { _icon = value; }
    }
    private int _fee = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"fee", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fee
    {
      get { return _fee; }
      set { _fee = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ServerChangeSyn")]
  public partial class ServerChangeSyn : global::ProtoBuf.IExtensible
  {
    public ServerChangeSyn() {}
    
    private string _msgServerAddr = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgServerAddr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string msgServerAddr
    {
      get { return _msgServerAddr; }
      set { _msgServerAddr = value; }
    }
    private string _gameServerAddr = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"gameServerAddr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gameServerAddr
    {
      get { return _gameServerAddr; }
      set { _gameServerAddr = value; }
    }
    private string _hallServerAddr = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"hallServerAddr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hallServerAddr
    {
      get { return _hallServerAddr; }
      set { _hallServerAddr = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LogoutSyn")]
  public partial class LogoutSyn : global::ProtoBuf.IExtensible
  {
    public LogoutSyn() {}
    
    private string _reason = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"reason", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string reason
    {
      get { return _reason; }
      set { _reason = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}