//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Assets/ProtoBuffMsg/MJBase.proto
namespace packet.mj
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameOperation")]
  public partial class GameOperation : global::ProtoBuf.IExtensible
  {
    public GameOperation() {}
    
    private packet.mj.GameOperType _operType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"operType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public packet.mj.GameOperType operType
    {
      get { return _operType; }
      set { _operType = value; }
    }
    private byte[] _content = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"GameOperType")]
    public enum GameOperType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameOperStartSyn", Value=7001)]
      GameOperStartSyn = 7001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameOperHandCardSyn", Value=7002)]
      GameOperHandCardSyn = 7002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameOperPublicInfoSyn", Value=7003)]
      GameOperPublicInfoSyn = 7003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameOperPlayerHuSyn", Value=7004)]
      GameOperPlayerHuSyn = 7004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameOperPlayerActionNotify", Value=7005)]
      GameOperPlayerActionNotify = 7005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameOperActorSyn", Value=7006)]
      GameOperActorSyn = 7006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameOperPlayerActionSyn", Value=7007)]
      GameOperPlayerActionSyn = 7007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameOperBaoChangeSyn", Value=7008)]
      GameOperBaoChangeSyn = 7008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameOperReNofity", Value=7009)]
      GameOperReNofity = 7009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameOperFinalSettleSyn", Value=7010)]
      GameOperFinalSettleSyn = 7010
    }
  
}