//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Assets/ProtoBuffMsg/Msg.proto
namespace packet.game
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MarqueeMsgSyn")]
  public partial class MarqueeMsgSyn : global::ProtoBuf.IExtensible
  {
    public MarqueeMsgSyn() {}
    
    private string _content = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private string _playerSetting = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerSetting", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string playerSetting
    {
      get { return _playerSetting; }
      set { _playerSetting = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MailMsgModel")]
  public partial class MailMsgModel : global::ProtoBuf.IExtensible
  {
    public MailMsgModel() {}
    
    private long _mailId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mailId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long mailId
    {
      get { return _mailId; }
      set { _mailId = value; }
    }
    private string _title = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _content = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private int _attachType = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"attachType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int attachType
    {
      get { return _attachType; }
      set { _attachType = value; }
    }
    private int _attachNum = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"attachNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int attachNum
    {
      get { return _attachNum; }
      set { _attachNum = value; }
    }
    private int _state = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private long _sendTime = default(long);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"sendTime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long sendTime
    {
      get { return _sendTime; }
      set { _sendTime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReadMailMsgRequest")]
  public partial class ReadMailMsgRequest : global::ProtoBuf.IExtensible
  {
    public ReadMailMsgRequest() {}
    
    private long _msgId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"msgId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long msgId
    {
      get { return _msgId; }
      set { _msgId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"NewMailMsgSyn")]
  public partial class NewMailMsgSyn : global::ProtoBuf.IExtensible
  {
    public NewMailMsgSyn() {}
    
    private readonly global::System.Collections.Generic.List<packet.game.MailMsgModel> _mails = new global::System.Collections.Generic.List<packet.game.MailMsgModel>();
    [global::ProtoBuf.ProtoMember(1, Name=@"mails", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<packet.game.MailMsgModel> mails
    {
      get { return _mails; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReceiveMailAttachRequest")]
  public partial class ReceiveMailAttachRequest : global::ProtoBuf.IExtensible
  {
    public ReceiveMailAttachRequest() {}
    
    private long _mailId = default(long);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"mailId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(long))]
    public long mailId
    {
      get { return _mailId; }
      set { _mailId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActAndNoticeMsgSyn")]
  public partial class ActAndNoticeMsgSyn : global::ProtoBuf.IExtensible
  {
    public ActAndNoticeMsgSyn() {}
    
    private readonly global::System.Collections.Generic.List<packet.game.ActMsgModel> _acts = new global::System.Collections.Generic.List<packet.game.ActMsgModel>();
    [global::ProtoBuf.ProtoMember(1, Name=@"acts", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<packet.game.ActMsgModel> acts
    {
      get { return _acts; }
    }
  
    private string _notice = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"notice", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string notice
    {
      get { return _notice; }
      set { _notice = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ActMsgModel")]
  public partial class ActMsgModel : global::ProtoBuf.IExtensible
  {
    public ActMsgModel() {}
    
    private string _title = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"title", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string title
    {
      get { return _title; }
      set { _title = value; }
    }
    private string _content = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string content
    {
      get { return _content; }
      set { _content = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}