//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Assets/ProtoBuffMsg/MsgBase.proto
namespace packet.msgbase
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PacketBase")]
  public partial class PacketBase : global::ProtoBuf.IExtensible
  {
    public PacketBase() {}
    
    private packet.msgbase.PacketType _packetType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"packetType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public packet.msgbase.PacketType packetType
    {
      get { return _packetType; }
      set { _packetType = value; }
    }
    private int _code = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int code
    {
      get { return _code; }
      set { _code = value; }
    }
    private string _msg = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private byte[] _data = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  

    //这个下面是全部的消息编号
    [global::ProtoBuf.ProtoContract(Name=@"PacketType")]
    public enum PacketType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Dump", Value=1)]
      Dump = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HEARTBEAT", Value=1001)]
      HEARTBEAT = 1001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LoginRequest", Value=1002)]
      LoginRequest = 1002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AuthRequest", Value=1003)]
      AuthRequest = 1003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GlobalMsgSyn", Value=1004)]
      GlobalMsgSyn = 1004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VistorRegisterRequest", Value=1005)]
      VistorRegisterRequest = 1005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VistorRegisterResponse", Value=1006)]
      VistorRegisterResponse = 1006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RegisterRequest", Value=1007)]
      RegisterRequest = 1007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RegisterResponse", Value=1008)]
      RegisterResponse = 1008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"UserInfoSyn", Value=1009)]
      UserInfoSyn = 1009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ModifyUserInfoRequest", Value=1010)]
      ModifyUserInfoRequest = 1010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnrollRequest", Value=2001)]
      EnrollRequest = 2001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReadyRequest", Value=2002)]
      ReadyRequest = 2002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChangeDeskRequest", Value=2003)]
      ChangeDeskRequest = 2003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"KickOutSyn", Value=2004)]
      KickOutSyn = 2004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ChatRequest", Value=2005)]
      ChatRequest = 2005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Back2HallRequest", Value=2006)]
      Back2HallRequest = 2006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerGamingSyn", Value=2007)]
      PlayerGamingSyn = 2007,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerSitSyn", Value=2008)]
      PlayerSitSyn = 2008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"AwayGameRequest", Value=2009)]
      AwayGameRequest = 2009,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerAwaySyn", Value=2010)]
      PlayerAwaySyn = 2010,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerComebackSyn", Value=2011)]
      PlayerComebackSyn = 2011,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerOfflineSyn", Value=2012)]
      PlayerOfflineSyn = 2012,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerReconnectSyn", Value=2013)]
      PlayerReconnectSyn = 2013,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ExitGameRequest", Value=2014)]
      ExitGameRequest = 2014,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerExitSyn", Value=2015)]
      PlayerExitSyn = 2015,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReadySyn", Value=2016)]
      ReadySyn = 2016,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameStartSyn", Value=2017)]
      GameStartSyn = 2017,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CreateVipRoomRequest", Value=2018)]
      CreateVipRoomRequest = 2018,
            
      [global::ProtoBuf.ProtoEnum(Name=@"EnterVipRoomRequest", Value=2019)]
      EnterVipRoomRequest = 2019,
            
      [global::ProtoBuf.ProtoEnum(Name=@"KickPlayerRequest", Value=2020)]
      KickPlayerRequest = 2020,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VipRoomListReuqest", Value=2021)]
      VipRoomListReuqest = 2021,
            
      [global::ProtoBuf.ProtoEnum(Name=@"VipRoomListSyn", Value=2022)]
      VipRoomListSyn = 2022,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DismissVipRoomRequest", Value=2023)]
      DismissVipRoomRequest = 2023,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameChatMsgRequest", Value=2024)]
      GameChatMsgRequest = 2024,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameChatMsgSyn", Value=2025)]
      GameChatMsgSyn = 2025,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HangupRequest", Value=2026)]
      HangupRequest = 2026,
            
      [global::ProtoBuf.ProtoEnum(Name=@"HangupSyn", Value=2027)]
      HangupSyn = 2027,
            
      [global::ProtoBuf.ProtoEnum(Name=@"CancelHangupRequest", Value=2028)]
      CancelHangupRequest = 2028,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DeskDestorySyn", Value=2029)]
      DeskDestorySyn = 2029,
            
      [global::ProtoBuf.ProtoEnum(Name=@"LogoutSyn", Value=2030)]
      LogoutSyn = 2030,
            
      [global::ProtoBuf.ProtoEnum(Name=@"DissmissVoteSyn", Value=2031)]
      DissmissVoteSyn = 2031,
            
      [global::ProtoBuf.ProtoEnum(Name=@"PlayerGamingSynInquire", Value=2032)]
      PlayerGamingSynInquire = 2032,
            
      [global::ProtoBuf.ProtoEnum(Name=@"BackGameRequest", Value=2033)]
      BackGameRequest = 2033,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GameOperation", Value=3001)]
      GameOperation = 3001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReadMailMsgRequest", Value=4001)]
      ReadMailMsgRequest = 4001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MarqueeMsgSyn", Value=4002)]
      MarqueeMsgSyn = 4002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"NewMailMsgSyn", Value=4005)]
      NewMailMsgSyn = 4005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ReceiveMailAttachRequest", Value=4006)]
      ReceiveMailAttachRequest = 4006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ActAndNoticeMsgSyn", Value=4008)]
      ActAndNoticeMsgSyn = 4008,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoomResultRequest", Value=5001)]
      RoomResultRequest = 5001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoomResultResponse", Value=5002)]
      RoomResultResponse = 5002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GenOrderRequest", Value=6001)]
      GenOrderRequest = 6001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"GenOrderResponse", Value=6002)]
      GenOrderResponse = 6002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ConfirmOrderRequest", Value=6003)]
      ConfirmOrderRequest = 6003,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ConfirmOrderReqsponse", Value=6004)]
      ConfirmOrderReqsponse = 6004,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MallProductRequest", Value=6005)]
      MallProductRequest = 6005,
            
      [global::ProtoBuf.ProtoEnum(Name=@"MallProductResponse", Value=6006)]
      MallProductResponse = 6006,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RankRequest", Value=7001)]
      RankRequest = 7001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RankSyn", Value=7002)]
      RankSyn = 7002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoomConfigRequest", Value=8001)]
      RoomConfigRequest = 8001,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RoomConfigResponse", Value=8002)]
      RoomConfigResponse = 8002,
            
      [global::ProtoBuf.ProtoEnum(Name=@"ServerChangeSyn", Value=8003)]
      ServerChangeSyn = 8003
    }
  
}