//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     这段代码是由一个工具生成的。
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Assets/ProtoBuffMsg/MsgGame.proto
namespace packet.game
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CreateVipRoomRequest")]
  public partial class CreateVipRoomRequest : global::ProtoBuf.IExtensible
  {
    public CreateVipRoomRequest() {}
    
    private int _quanNum = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"quanNum", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int quanNum
    {
      get { return _quanNum; }
      set { _quanNum = value; }
    }
    private int _wangfa = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"wangfa", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int wangfa
    {
      get { return _wangfa; }
      set { _wangfa = value; }
    }
    private int _vipRoomType = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"vipRoomType", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int vipRoomType
    {
      get { return _vipRoomType; }
      set { _vipRoomType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VipRoomListSyn")]
  public partial class VipRoomListSyn : global::ProtoBuf.IExtensible
  {
    public VipRoomListSyn() {}
    
    private readonly global::System.Collections.Generic.List<packet.game.VipRoomModel> _roomList = new global::System.Collections.Generic.List<packet.game.VipRoomModel>();
    [global::ProtoBuf.ProtoMember(1, Name=@"roomList", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<packet.game.VipRoomModel> roomList
    {
      get { return _roomList; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VipRoomModel")]
  public partial class VipRoomModel : global::ProtoBuf.IExtensible
  {
    public VipRoomModel() {}
    
    private string _code = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string code
    {
      get { return _code; }
      set { _code = value; }
    }
    private string _name = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"name", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string name
    {
      get { return _name; }
      set { _name = value; }
    }
    private int _roomType = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private int _quanNum;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"quanNum", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int quanNum
    {
      get { return _quanNum; }
      set { _quanNum = value; }
    }
    private int _wangfa = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"wangfa", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int wangfa
    {
      get { return _wangfa; }
      set { _wangfa = value; }
    }
    private readonly global::System.Collections.Generic.List<packet.game.PlayerModel> _players = new global::System.Collections.Generic.List<packet.game.PlayerModel>();
    [global::ProtoBuf.ProtoMember(6, Name=@"players", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<packet.game.PlayerModel> players
    {
      get { return _players; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerModel")]
  public partial class PlayerModel : global::ProtoBuf.IExtensible
  {
    public PlayerModel() {}
    
    private int _position;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int position
    {
      get { return _position; }
      set { _position = value; }
    }
    private string _nickName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private int _playerId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _coin;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private int _state;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private int _online;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"online", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int online
    {
      get { return _online; }
      set { _online = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DismissVipRoomRequest")]
  public partial class DismissVipRoomRequest : global::ProtoBuf.IExtensible
  {
    public DismissVipRoomRequest() {}
    
    private string _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"VipRoomPlayersRequest")]
  public partial class VipRoomPlayersRequest : global::ProtoBuf.IExtensible
  {
    public VipRoomPlayersRequest() {}
    
    private string _code;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string code
    {
      get { return _code; }
      set { _code = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KickPlayerRequest")]
  public partial class KickPlayerRequest : global::ProtoBuf.IExtensible
  {
    public KickPlayerRequest() {}
    
    private string _code = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"code", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string code
    {
      get { return _code; }
      set { _code = value; }
    }
    private int _playerId = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnrollRequest")]
  public partial class EnrollRequest : global::ProtoBuf.IExtensible
  {
    public EnrollRequest() {}
    
    private string _gameId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private string _matchId = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"matchId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string matchId
    {
      get { return _matchId; }
      set { _matchId = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _cards = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(3, Name=@"cards", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public global::System.Collections.Generic.List<int> cards
    {
      get { return _cards; }
    }
  
    private string _roomCode = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"roomCode", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string roomCode
    {
      get { return _roomCode; }
      set { _roomCode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"EnrollResponse")]
  public partial class EnrollResponse : global::ProtoBuf.IExtensible
  {
    public EnrollResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerGamingSyn")]
  public partial class PlayerGamingSyn : global::ProtoBuf.IExtensible
  {
    public PlayerGamingSyn() {}
    
    private string _gameId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private string _matchId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"matchId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string matchId
    {
      get { return _matchId; }
      set { _matchId = value; }
    }
    private string _roomId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"roomId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string roomId
    {
      get { return _roomId; }
      set { _roomId = value; }
    }
    private string _deskId;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"deskId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string deskId
    {
      get { return _deskId; }
      set { _deskId = value; }
    }
    private int _wanfa;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"wanfa", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wanfa
    {
      get { return _wanfa; }
      set { _wanfa = value; }
    }
    private int _roomType = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"roomType", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int roomType
    {
      get { return _roomType; }
      set { _roomType = value; }
    }
    private int _totalQuan = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"totalQuan", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int totalQuan
    {
      get { return _totalQuan; }
      set { _totalQuan = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerSitSyn")]
  public partial class PlayerSitSyn : global::ProtoBuf.IExtensible
  {
    public PlayerSitSyn() {}
    
    private int _position;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int position
    {
      get { return _position; }
      set { _position = value; }
    }
    private string _nickName;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private int _playerId;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _coin;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private int _state;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private int _online;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"online", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int online
    {
      get { return _online; }
      set { _online = value; }
    }
    private string _headImg = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"headImg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headImg
    {
      get { return _headImg; }
      set { _headImg = value; }
    }
    private int _sex = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private int _score = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"score", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int score
    {
      get { return _score; }
      set { _score = value; }
    }
    private int _away = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"away", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int away
    {
      get { return _away; }
      set { _away = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerAwaySyn")]
  public partial class PlayerAwaySyn : global::ProtoBuf.IExtensible
  {
    public PlayerAwaySyn() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerOfflineSyn")]
  public partial class PlayerOfflineSyn : global::ProtoBuf.IExtensible
  {
    public PlayerOfflineSyn() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerComebackSyn")]
  public partial class PlayerComebackSyn : global::ProtoBuf.IExtensible
  {
    public PlayerComebackSyn() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerReconnectSyn")]
  public partial class PlayerReconnectSyn : global::ProtoBuf.IExtensible
  {
    public PlayerReconnectSyn() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerExitSyn")]
  public partial class PlayerExitSyn : global::ProtoBuf.IExtensible
  {
    public PlayerExitSyn() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReadySyn")]
  public partial class ReadySyn : global::ProtoBuf.IExtensible
  {
    public ReadySyn() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private int _state;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"state", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int state
    {
      get { return _state; }
      set { _state = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeDeskRequest")]
  public partial class ChangeDeskRequest : global::ProtoBuf.IExtensible
  {
    public ChangeDeskRequest() {}
    
    private int _playerId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"playerId", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int playerId
    {
      get { return _playerId; }
      set { _playerId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ChangeDeskResponse")]
  public partial class ChangeDeskResponse : global::ProtoBuf.IExtensible
  {
    public ChangeDeskResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameStartSyn")]
  public partial class GameStartSyn : global::ProtoBuf.IExtensible
  {
    public GameStartSyn() {}
    
    private string _deskId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"deskId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string deskId
    {
      get { return _deskId; }
      set { _deskId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameMsgSyn")]
  public partial class GameMsgSyn : global::ProtoBuf.IExtensible
  {
    public GameMsgSyn() {}
    
    private int _flag;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private string _gameId;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"gameId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string gameId
    {
      get { return _gameId; }
      set { _gameId = value; }
    }
    private string _matchId = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"matchId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string matchId
    {
      get { return _matchId; }
      set { _matchId = value; }
    }
    private string _msg = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameChatMsgRequest")]
  public partial class GameChatMsgRequest : global::ProtoBuf.IExtensible
  {
    public GameChatMsgRequest() {}
    
    private byte[] _content = null;
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"content", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] content
    {
      get { return _content; }
      set { _content = value; }
    }
    private int _contentType = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"contentType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int contentType
    {
      get { return _contentType; }
      set { _contentType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"GameChatMsgSyn")]
  public partial class GameChatMsgSyn : global::ProtoBuf.IExtensible
  {
    public GameChatMsgSyn() {}
    
    private string _deskId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"deskId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string deskId
    {
      get { return _deskId; }
      set { _deskId = value; }
    }
    private int _position = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int position
    {
      get { return _position; }
      set { _position = value; }
    }
    private byte[] _data = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"data", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] data
    {
      get { return _data; }
      set { _data = value; }
    }
    private int _contentType = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"contentType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int contentType
    {
      get { return _contentType; }
      set { _contentType = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"HangupSyn")]
  public partial class HangupSyn : global::ProtoBuf.IExtensible
  {
    public HangupSyn() {}
    
    private int _position = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int position
    {
      get { return _position; }
      set { _position = value; }
    }
    private int _status = default(int);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"status", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int status
    {
      get { return _status; }
      set { _status = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DeskDestorySyn")]
  public partial class DeskDestorySyn : global::ProtoBuf.IExtensible
  {
    public DeskDestorySyn() {}
    
    private string _deskId = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"deskId", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string deskId
    {
      get { return _deskId; }
      set { _deskId = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"DissmissVoteSyn")]
  public partial class DissmissVoteSyn : global::ProtoBuf.IExtensible
  {
    public DissmissVoteSyn() {}
    
    private int _position = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"position", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int position
    {
      get { return _position; }
      set { _position = value; }
    }
    private bool _agree = default(bool);
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"agree", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool agree
    {
      get { return _agree; }
      set { _agree = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"PlayerGamingSynInquire")]
  public partial class PlayerGamingSynInquire : global::ProtoBuf.IExtensible
  {
    public PlayerGamingSynInquire() {}
    
    private bool _isGaming = default(bool);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"isGaming", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool isGaming
    {
      get { return _isGaming; }
      set { _isGaming = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}