//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Assets/ProtoBuffMsg/User.proto
namespace packet.user
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginRequest")]
  public partial class LoginRequest : global::ProtoBuf.IExtensible
  {
    public LoginRequest() {}
    
    private string _username;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"username", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string username
    {
      get { return _username; }
      set { _username = value; }
    }
    private string _passward;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"passward", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string passward
    {
      get { return _passward; }
      set { _passward = value; }
    }
    private int _type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int type
    {
      get { return _type; }
      set { _type = value; }
    }
    private string _version = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
    private int _deviceFlag = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"deviceFlag", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int deviceFlag
    {
      get { return _deviceFlag; }
      set { _deviceFlag = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"LoginResponse")]
  public partial class LoginResponse : global::ProtoBuf.IExtensible
  {
    public LoginResponse() {}
    
    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _token = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private string _msgServerAddr = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"msgServerAddr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string msgServerAddr
    {
      get { return _msgServerAddr; }
      set { _msgServerAddr = value; }
    }
    private string _gameServerAddr = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"gameServerAddr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string gameServerAddr
    {
      get { return _gameServerAddr; }
      set { _gameServerAddr = value; }
    }
    private string _hallServerAddr = "";
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"hallServerAddr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string hallServerAddr
    {
      get { return _hallServerAddr; }
      set { _hallServerAddr = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"UserInfoSyn")]
  public partial class UserInfoSyn : global::ProtoBuf.IExtensible
  {
    public UserInfoSyn() {}
    
    private int _userId = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _nickName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private string _headImg = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"headImg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headImg
    {
      get { return _headImg; }
      set { _headImg = value; }
    }
    private int _coin = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"coin", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int coin
    {
      get { return _coin; }
      set { _coin = value; }
    }
    private int _fanka = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"fanka", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fanka
    {
      get { return _fanka; }
      set { _fanka = value; }
    }
    private int _continueWinCount = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"continueWinCount", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int continueWinCount
    {
      get { return _continueWinCount; }
      set { _continueWinCount = value; }
    }
    private int _totalGameCount = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"totalGameCount", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int totalGameCount
    {
      get { return _totalGameCount; }
      set { _totalGameCount = value; }
    }
    private double _winRate = default(double);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"winRate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double winRate
    {
      get { return _winRate; }
      set { _winRate = value; }
    }
    private string _ip = "";
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"ip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ip
    {
      get { return _ip; }
      set { _ip = value; }
    }
    private string _maxFanType = "";
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"maxFanType", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string maxFanType
    {
      get { return _maxFanType; }
      set { _maxFanType = value; }
    }
    private readonly global::System.Collections.Generic.List<int> _handcard = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(11, Name=@"handcard", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> handcard
    {
      get { return _handcard; }
    }
  
    private readonly global::System.Collections.Generic.List<int> _downcard = new global::System.Collections.Generic.List<int>();
    [global::ProtoBuf.ProtoMember(12, Name=@"downcard", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public global::System.Collections.Generic.List<int> downcard
    {
      get { return _downcard; }
    }
  
    private bool _createMultiRoom = default(bool);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"createMultiRoom", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(default(bool))]
    public bool createMultiRoom
    {
      get { return _createMultiRoom; }
      set { _createMultiRoom = value; }
    }
    private int _sex = default(int);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AuthRequest")]
  public partial class AuthRequest : global::ProtoBuf.IExtensible
  {
    public AuthRequest() {}
    
    private int _userId;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"userId", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    public int userId
    {
      get { return _userId; }
      set { _userId = value; }
    }
    private string _token;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"token", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string token
    {
      get { return _token; }
      set { _token = value; }
    }
    private string _version = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"AuthResponse")]
  public partial class AuthResponse : global::ProtoBuf.IExtensible
  {
    public AuthResponse() {}
    
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ModifyUserInfoRequest")]
  public partial class ModifyUserInfoRequest : global::ProtoBuf.IExtensible
  {
    public ModifyUserInfoRequest() {}
    
    private string _headImg = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"headImg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string headImg
    {
      get { return _headImg; }
      set { _headImg = value; }
    }
    private string _nickName = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"nickName", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string nickName
    {
      get { return _nickName; }
      set { _nickName = value; }
    }
    private int _sex = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"sex", DataFormat = global::ProtoBuf.DataFormat.ZigZag)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int sex
    {
      get { return _sex; }
      set { _sex = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}